# Keycloak OIDC provider for integration testing.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: keycloak-realm
    files:
      - complytime-realm.json
