# Kustomize resources for Grafana — compliance dashboard UI.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pvc.yaml
  - configmap.yaml
  - dashboards.yaml
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: grafana-dashboard-compliance
    options:
      disableNameSuffixHash: true
    files:
      - compliance-overview.json
