# Persistent storage for Grafana dashboards and settings.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
