# Persistent storage for Loki log data. ReadWriteMany for EFS compatibility.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-storage
  labels:
    paas.redhat.com/appcode: CPLY-001
  annotations:
    Provisioner: efs.csi.aws.com
    volume.beta.kubernetes.io/storage-provisioner: efs.csi.aws.com
    AppCode: CPLY-001
    kubernetes.io/reclaimPolicy: Delete
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
