name: Security

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: none
  id-token: none
  security-events: none
  packages: none

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call_reusable_vuln_scan:
    name: Vulnerability Scan
    uses: complytime/org-infra/.github/workflows/reusable_vuln_scan.yml@2c193416adbc621a64021ace52bf57114d703888 # v0.3.1
    permissions:
      contents: read
      actions: read
      security-events: write
      packages: write
      id-token: write
    with:
      enable_trivy_source: true

  call_reusable_security:
    name: OpenSSF Scorecards
    uses: complytime/org-infra/.github/workflows/reusable_security.yml@bbd7194995388f96dd28c0c0792d406c8a249140 # v0.4.0
    permissions:
      contents: read
      id-token: write
      security-events: write
