name: Scheduled Security

on:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read
  actions: none
  id-token: none
  security-events: none

jobs:
  call_reusable_scheduled:
    name: Scheduled Scan
    uses: complytime/org-infra/.github/workflows/reusable_scheduled.yml@bd3718a218d649b093269fe4a979c4a4632dfad2 # v0.8.0
    permissions:
      contents: read
      actions: read
      security-events: write
      id-token: write
